In [11]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


In [12]:
data_yelp = pd.read_csv("/content/yelp_labelled.txt", sep="\t", header=None)
data_yelp.head()

0  1
0                           Wow... Loved this place.  1
1                                 Crust is not good.  0
2          Not tasty and the texture was just nasty.  0
3  Stopped by during the late May bank holiday of...  1
4  The selection on the menu was great and so wer...  1

In [13]:
column_names = ['Review', 'Sentiment']
data_yelp.columns = column_names
data_yelp.head()

Review  Sentiment
0                           Wow... Loved this place.          1
1                                 Crust is not good.          0
2          Not tasty and the texture was just nasty.          0
3  Stopped by during the late May bank holiday of...          1
4  The selection on the menu was great and so wer...          1

In [14]:
data_yelp.shape

(1000, 2)

In [15]:
data_amazon = pd.read_csv("/content/amazon_cells_labelled.txt", sep="\t", header=None)
data_amazon.head()

0  1
0  So there is no way for me to plug it in here i...  0
1                        Good case, Excellent value.  1
2                             Great for the jawbone.  1
3  Tied to charger for conversations lasting more...  0
4                                  The mic is great.  1

In [16]:
column_names = ['Review', 'Sentiment']
data_amazon.columns = column_names
data_amazon.head()


Review  Sentiment
0  So there is no way for me to plug it in here i...          0
1                        Good case, Excellent value.          1
2                             Great for the jawbone.          1
3  Tied to charger for conversations lasting more...          0
4                                  The mic is great.          1

In [17]:
data_amazon.shape

(1000, 2)

In [18]:
data_imdb = pd.read_csv("/content/imdb_labelled.txt", sep="\t", header=None)
data_imdb.head()

0  1
0  A very, very, very slow-moving, aimless movie ...  0
1  Not sure who was more lost - the flat characte...  0
2  Attempting artiness with black & white and cle...  0
3       Very little music or anything to speak of.    0
4  The best scene in the movie was when Gerardo i...  1

In [19]:
data_imdb.columns = column_names
data_imdb.head()

Review  Sentiment
0  A very, very, very slow-moving, aimless movie ...          0
1  Not sure who was more lost - the flat characte...          0
2  Attempting artiness with black & white and cle...          0
3       Very little music or anything to speak of.            0
4  The best scene in the movie was when Gerardo i...          1

In [20]:
data_imdb.shape

(748, 2)

In [21]:
data = pd.concat([data_yelp, data_amazon, data_imdb], ignore_index=True)
data.head()

Review  Sentiment
0                           Wow... Loved this place.          1
1                                 Crust is not good.          0
2          Not tasty and the texture was just nasty.          0
3  Stopped by during the late May bank holiday of...          1
4  The selection on the menu was great and so wer...          1

In [22]:
data.shape

(2748, 2)

In [23]:
data.head()

Review  Sentiment
0                           Wow... Loved this place.          1
1                                 Crust is not good.          0
2          Not tasty and the texture was just nasty.          0
3  Stopped by during the late May bank holiday of...          1
4  The selection on the menu was great and so wer...          1

In [24]:
data['Sentiment'].value_counts()

Sentiment
1    1386
0    1362
Name: count, dtype: int64

In [25]:
data.isnull().sum()

Review       0
Sentiment    0
dtype: int64

In [26]:
x = data["Sentiment"]
y = data["Review"]

**data cleaning**

In [27]:
import string

In [28]:
punct = string.punctuation
punct

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [29]:
from spacy.lang.en.stop_words import STOP_WORDS
stopwords = list(STOP_WORDS)
stopwords

['within',
 'most',
 'also',
 'yours',
 'we',
 'fifteen',
 'side',
 'behind',
 'too',
 'therefore',
 'into',
 'along',
 'than',
 'even',
 'back',
 'throughout',
 'more',
 'see',
 'must',
 'unless',
 'perhaps',
 "'ll",
 'never',
 'quite',
 'their',
 'via',
 'among',
 'next',
 'afterwards',
 'few',
 'otherwise',
 "'s",
 'others',
 'he',
 'this',
 'each',
 'everything',
 'during',
 'nor',
 'and',
 'used',
 'twenty',
 'whereupon',
 'whether',
 'someone',
 'so',
 'four',
 'after',
 'may',
 'by',
 'sometimes',
 'once',
 'three',
 '’m',
 "'d",
 'moreover',
 'to',
 'hence',
 'why',
 'became',
 'meanwhile',
 'because',
 'thus',
 'on',
 'which',
 'at',
 'give',
 'cannot',
 'these',
 'but',
 'has',
 'been',
 'above',
 'off',
 'beforehand',
 'myself',
 'did',
 'being',
 'nobody',
 'please',
 '‘ll',
 'had',
 'neither',
 'nowhere',
 "'m",
 'n‘t',
 'five',
 'forty',
 'can',
 'still',
 'both',
 'ever',
 'eight',
 'you',
 'through',
 'yet',
 'some',
 'whose',
 'itself',
 'noone',
 'much',
 'she',
 'whi

In [30]:
import spacy
nlp = spacy.load('en_core_web_sm')

def text_data_cleaning(sentence):
  doc = nlp(sentence)
  tokens = []
  for token in doc:
    if token.lemma_ != "-PRON-":
      temp = token.lemma_.lower().strip()
    else:
      temp = token.lower_
    tokens.append(temp)

  cleaned_tokens = []
  for token in tokens:
    if token not in stopwords and token not in punct:
      cleaned_tokens.append(token)
  return cleaned_tokens
#

In [31]:
text_data_cleaning("Hello all, It's a beautiful day outside there!")



['hello', 'beautiful', 'day', 'outside']

VECTORIZATION FEATURE ENGINEERING (TF-DIF)

In [32]:
from sklearn.svm import LinearSVC
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.pipeline import Pipeline

In [33]:
tfidf = TfidfVectorizer(tokenizer=text_data_cleaning)
classifier = LinearSVC()

train model


In [34]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)

In [35]:
x_train.shape, x_test.shape

((2198,), (550,))

In [37]:
y_train.head()

2572    An Italian reviewer called this "a small, grea...
526                          And it was way to expensive.
1509    As an earlier review noted, plug in this charg...
144     Nice blanket of moz over top but i feel like t...
2483    The film gives meaning to the phrase, "Never i...
Name: Review, dtype: object

In [40]:
clf = Pipeline([('tfidf', tfidf), ('clf', classifier)])
clf

Pipeline(steps=[('tfidf',
                 TfidfVectorizer(tokenizer=<function text_data_cleaning at 0x7be6f3c040d0>)),
                ('clf', LinearSVC())])

In [41]:
clf.fit(y_train, x_train)

/usr/local/lib/python3.10/dist-packages/sklearn/feature_extraction/text.py:525: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/svm/_classes.py:32: FutureWarning: The default value of `dual` will change from `True` to `'auto'` in 1.5. Set the value of `dual` explicitly to suppress the warning.
  warnings.warn(


Pipeline(steps=[('tfidf',
                 TfidfVectorizer(tokenizer=<function text_data_cleaning at 0x7be6f3c040d0>)),
                ('clf', LinearSVC())])

In [42]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [43]:
y_pred = clf.predict(y_test)

In [44]:
confusion_matrix(x_test, y_pred)

array([[201,  78],
       [ 50, 221]])

In [45]:
print(classification_report(x_test, y_pred))

              precision    recall  f1-score   support

           0       0.80      0.72      0.76       279
           1       0.74      0.82      0.78       271

    accuracy                           0.77       550
   macro avg       0.77      0.77      0.77       550
weighted avg       0.77      0.77      0.77       550



In [46]:
accuracy_score(x_test, y_pred)

0.7672727272727272

In [47]:
clf.predict(["Wow, I am learning Natural Language Processing in fun fashion!"])

array([1])

In [48]:
clf.predict(["It's hard to learn new things!"])

array([0])